### ISSUE TITLE
Can't read barcodes other than code-128

### ISSUE THREAD

**Issue by MikeJWms** [sin-tanaka/vue-quagga#14]
Hi,

I'm having a problem reading barcodes other than code-128. Tested in Chrome and Safari, both on desktop and iPhone. Here is the quick test app I put together which reproduces the issue: [https://github.com/MikeJWms/vue-quagga-test](url). It's just the example code in the readme wrapped in a vue app.

It's probably something silly that I'm doing, but I've spend the whole day on this with not luck so any help would be appreciated.

Thanks,

Mike

**Comment by MikeJWms** [comment]
Figured out there's a typo in the readme's basic example. `:readerType` should be `:readerTypes` with an 's'. Because of this the component defaults to decoding code-128.

**Comment by MikeJWms** [comment]
Just submitted pull request #15 to fix this issue.

**Comment by sin-tanaka** [comment]
Sorry FixTypo
