### ISSUE TITLE
DOMException

### ISSUE THREAD

**Issue by ionciubotaru** [sin-tanaka/vue-quagga#19]
I tried the example, and I got this error in console:
DOMException (anonymous) @ Scanner.vue?e41e:114

Example is in the file below:
[test.zip](https://github.com/sin-tanaka/vue-quagga/files/3076438/test.zip)

Please help.
Thank you for `vue-quagga`

**Comment by devlinpadayachee** [comment]
Getting the same error: Any fix for this?

**Comment by ionciubotaru** [comment]
Solved, there is no error. 
If your setup is Desktop Chrome + Android Chrome, use Remote Debugging which allows your Android device to access your local server as localhost. https://developers.google.com/web/tools/chrome-devtools/remote-debugging/local-server

Or you can build and deploy your app to a https server.

Suggestion for @sin-tanaka please add error messages inside library

```
      } catch (error) {
        if (error.name === 'NotAllowedError') {
          this.error = "ERROR: you need to grant camera access permisson"
        } else if (error.name === 'NotFoundError') {
          this.error = "ERROR: no camera on this device"
        } else if (error.name === 'NotSupportedError') {
          this.error = "ERROR: secure context required (HTTPS, localhost)"
        } else if (error.name === 'NotReadableError') {
          this.error = "ERROR: is the camera already in use?"
        } else if (error.name === 'OverconstrainedError') {
          this.error = "ERROR: installed cameras are not suitable"
        } else if (error.name === 'StreamApiNotSupportedError') {
          this.error = "ERROR: Stream API is not supported in this browser"
        }
```
