### ISSUE TITLE
Can't turn the camera off

### ISSUE THREAD

**Issue by ribas14** [sin-tanaka/vue-quagga#4]
I'm trying to close the camera after reading the barcode, but 

```
        QuaggaScanner.offDetected()
        this.QuaggaScanner.offDetected()
        QuaggaScanner.close()
        this.QuaggaScanner.close()
        Quagga.offDetected()
        this.Quagga.offDetected()
        Quagga.offDetected()
        this.Quagga.offDetected()
```
doesn't work, i get the following 

`__WEBPACK_IMPORTED_MODULE_0_vue_quaggajs__.QuaggaScanner.offDetected is not a function`

Any ideas?

**Comment by ribas14** [comment]
I kinda fixed importing the js file, 

`import Quagga from 'quagga';
`
after that 

```
        Quagga.offDetected()
        Quagga.stop()
```

worked, but I don't think that this is the right way

**Comment by shaqaruden** [comment]
I used a v-if to accomplish this. Not sure if its the best way.

I set a 'scanning' boolean to true or false to either show of hide the scanner


For example
```html
<button type="button" @click="scanning = true" name="button">Scan Barcode</button>
<quagga-scanner v-if="scanning" style="height: 480px; width: 640px;" :onDetected="logIt" :readerSize="readerSize" :readerType="'upc_reader'"></quagga-scanner>
...
methods: {
    logIt (data) {
      this.barcode = data.codeResult.code
      this.scanning = false
    },
  }
```

**Comment by adam91holt** [comment]
> I used a v-if to accomplish this. Not sure if its the best way.
> 
> I set a 'scanning' boolean to true or false to either show of hide the scanner
> 
> For example
> 
> ```
> <button type="button" @click="scanning = true" name="button">Scan Barcode</button>
> <quagga-scanner v-if="scanning" style="height: 480px; width: 640px;" :onDetected="logIt" :readerSize="readerSize" :readerType="'upc_reader'"></quagga-scanner>
> ...
> methods: {
>     logIt (data) {
>       this.barcode = data.codeResult.code
>       this.scanning = false
>     },
>   }
> ```

You may want to double check that, from my experience, the camera remains on using that approach in the background.

I have tried importing the Quagga library and doing as @ribas14 mentioned, however, this is giving me errors about Quagga being undefined. Does anyone else have a solution to closing the camera after a detection?
