### ISSUE TITLE
Error: getUserMedia is not defined

### ISSUE THREAD

**Issue by Stridesdata** [sin-tanaka/vue-quagga#44]
mounted:function mounted(){var _this=this;

quagga__WEBPACK_IMPORTED_MODULE_0___default.a.init(_this.quaggaState,function(err){
if(err){
return console.error(err);
}

I have searched for a solution for weeks now all to no avail. @sin-tanaka @dalezak or anyone. please help!!

**Comment by dev-rijan** [comment]
If you are trying on http site or localhost chrome doesn't allow to access camera. You can turn off this setting from chrome://flags/#unsafely-treat-insecure-origin-as-secure.

**Comment by Stridesdata** [comment]
Very correct
