### ISSUE TITLE
Please provide examples

### ISSUE THREAD

**Issue by clementvp** [sin-tanaka/vue-quagga#5]
Hello and thanks for this.

Do i pass onDetected and onProcessed in props in the quagga-sscanner component ?

Can you provide a fully functionnal example.
The documentation are a bit obfucated no ?

**Comment by jaumebalust** [comment]
This would be fantastic indeed

**Comment by jaumebalust** [comment]
I added a PR for this! feel free to check it out if you still have doubts.

**Comment by clementvp** [comment]
Ok thanks you very much, this example help me a lot !!!
The Pr looks good to me ;)

**Comment by sin-tanaka** [comment]
@jaumebalust @clementvp 
This PR merged. 

https://github.com/sin-tanaka/vue-quagga/pull/6

Thanks for added issue & PR!
